# Generated by Django 3.2.2 on 2024-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copia_doc_identidad', models.BooleanField(default=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
                ('tipo_doc', models.CharField(max_length=20)),
                ('num_doc', models.CharField(max_length=20)),
                ('img_firma', models.ImageField(upload_to='titulares/')),
                ('img_huella', models.ImageField(upload_to='titulares/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
