# Generated by Django 3.2.2 on 2024-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20240228_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='img_firma',
            field=models.ImageField(blank=True, null=True, upload_to='titulares/'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='img_huella',
            field=models.ImageField(blank=True, null=True, upload_to='titulares/'),
        ),
    ]
