# Generated by Django 3.2.2 on 2024-02-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20240228_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cel_wsp', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('posesion_informal', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('etapa', models.CharField(max_length=10)),
                ('direccion_fiscal', models.CharField(max_length=255)),
                ('descripcion_fisica', models.TextField()),
                ('tipo_uso', models.CharField(max_length=20)),
                ('servicios_basicos', models.CharField(max_length=100)),
                ('carta_poder', models.BooleanField(default=False)),
                ('hitos_consolidados', models.BooleanField(default=False)),
                ('acceso_a_via', models.BooleanField(default=False)),
                ('cantidad_lotes', models.IntegerField(default=0)),
                ('requiere_subdivision', models.BooleanField(default=False)),
                ('requiere_alineamiento', models.BooleanField(default=False)),
                ('apertura_de_via', models.BooleanField(default=False)),
                ('libre_de_riesgo', models.BooleanField(default=False)),
                ('req_transf_de_titular', models.BooleanField(default=False)),
                ('litigio_denuncia', models.BooleanField(default=False)),
                ('area_según_el_titular_representante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario1', models.TextField()),
                ('codigo_dlt', models.CharField(max_length=200)),
                ('hora', models.TimeField()),
                ('n_punto', models.IntegerField()),
                ('operador', models.CharField(max_length=100)),
                ('equipo_tp', models.CharField(max_length=100)),
                ('adjunta_toma_topografica', models.BooleanField(default=False)),
                ('tiempo_atmosferico', models.CharField(max_length=20)),
                ('comentario2', models.TextField()),
                ('titulares', models.ManyToManyField(related_name='actas', to='pos.Titular')),
            ],
        ),
        migrations.CreateModel(
            name='Colindancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente_nombre', models.CharField(max_length=100)),
                ('frente_distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fondo_nombre', models.CharField(max_length=100)),
                ('fondo_distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('derecha_nombre', models.CharField(max_length=100)),
                ('derecha_distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('izquierda_nombre', models.CharField(max_length=100)),
                ('izquierda_distancia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boceto', models.ImageField(upload_to='imagenes/')),
                ('firma_topografo', models.ImageField(upload_to='imagenes/')),
                ('firma_representante_comision', models.ImageField(upload_to='imagenes/')),
                ('firma_supervisor_campo', models.ImageField(upload_to='imagenes/')),
                ('comentario3', models.TextField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pos.acta')),
            ],
        ),
    ]
