# Generated by Django 3.2.2 on 2024-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_acta_colindancia_imagenacta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acta',
            old_name='area_según_el_titular_representante',
            new_name='area_segun_el_titular_representante',
        ),
        migrations.AlterField(
            model_name='acta',
            name='titulares',
            field=models.ManyToManyField(blank=True, related_name='actas', to='pos.Titular'),
        ),
    ]
