# Generated by Django 3.2.2 on 2024-03-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20240301_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='colindancia',
            name='acta',
            field=models.ForeignKey(default='20240301131457', on_delete=django.db.models.deletion.CASCADE, related_name='colindancias', to='pos.acta'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='acceso_a_via',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='apertura_de_via',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='carta_poder',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='hitos_consolidados',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='libre_de_riesgo',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='litigio_denuncia',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='req_transf_de_titular',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='requiere_alineamiento',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='acta',
            name='requiere_subdivision',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
