# Generated by Django 3.2.2 on 2024-03-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20240301_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='area_segun_el_titular_representante',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='colindancia',
            name='acta',
            field=models.ForeignKey(default='20240301132425', on_delete=django.db.models.deletion.CASCADE, related_name='colindancias', to='pos.acta'),
        ),
    ]
