# Generated by Django 3.2.2 on 2024-03-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20240301_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colindancia',
            name='acta',
            field=models.ForeignKey(default='20240301133511', on_delete=django.db.models.deletion.CASCADE, related_name='colindancias', to='pos.acta'),
        ),
    ]
