# Generated by Django 3.2.2 on 2024-03-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20240304_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colindancia',
            name='acta',
            field=models.ForeignKey(default='20240304100602', on_delete=django.db.models.deletion.CASCADE, related_name='colindancias', to='pos.acta'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='copia_doc_identidad',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
