# Generated by Django 3.2.2 on 2024-03-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20240304_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titular',
            name='img_firma',
        ),
        migrations.RemoveField(
            model_name='titular',
            name='img_huella',
        ),
        migrations.AddField(
            model_name='titular',
            name='pdf_documento',
            field=models.FileField(blank=True, null=True, upload_to='titulares/'),
        ),
        migrations.AlterField(
            model_name='colindancia',
            name='acta',
            field=models.ForeignKey(default='20240306082128', on_delete=django.db.models.deletion.CASCADE, related_name='colindancias', to='pos.acta'),
        ),
    ]
