# Generated by Django 3.2.2 on 2024-03-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20240306_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colindancia',
            name='acta',
            field=models.ForeignKey(default='20240306083448', on_delete=django.db.models.deletion.CASCADE, related_name='colindancias', to='pos.acta'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='tipo_doc',
            field=models.CharField(default='DNI', max_length=20, null=True),
        ),
    ]
