# Generated by Django 3.2.2 on 2024-06-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20240306_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colindancia',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='imagenacta',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='titular',
            name='acta',
        ),
        migrations.DeleteModel(
            name='Acta',
        ),
        migrations.DeleteModel(
            name='Colindancia',
        ),
        migrations.DeleteModel(
            name='ImagenActa',
        ),
        migrations.DeleteModel(
            name='Titular',
        ),
    ]
