# Generated by Django 3.2.2 on 2024-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20240605_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
