# Generated by Django 3.2.2 on 2024-06-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20240611_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='estado',
        ),
        migrations.AddField(
            model_name='sale',
            name='estado_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='estado_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='numero_mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.mesa'),
        ),
    ]
