# Generated by Django 3.2.2 on 2024-06-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_auto_20240612_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='numero_mesa',
            new_name='mesa',
        ),
    ]
