# Generated by Django 3.2.2 on 2024-06-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_alter_sale_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.mesa'),
        ),
    ]
