# Generated by Django 3.2.2 on 2024-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='stock'),
        ),
    ]
