# Generated by Django 3.2.2 on 2024-06-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(default='null', max_length=5, verbose_name='stock'),
        ),
    ]
